### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by minh132** [Tombs98/M3SNet#3]
When I run test.py use pretrained weights. I got this issues: 
===>Testing using weights:  ./pretrained/deblur_model_best_32.pth
Traceback (most recent call last):
  File "/home/minh/M3SNet/Deblur/test.py", line 36, in <module>
    model_restoration.cuda()
  File "/home/minh/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/minh/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/minh/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/minh/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/minh/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by Tombs98** [comment]
> 

You'll need to check if your machine has a gpu and if pytorch has a gpu version installed.

**Comment by minh132** [comment]
My machine has gpu NVIDIA GTX 1650 Ti and pytorch has already a gpu version
